//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthStat
    {
        public int StatId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int Steps { get; set; }
        public decimal WaterIntake { get; set; }
        public decimal SleepDuration { get; set; }
    
        public virtual User User { get; set; }
    }
}
